sudo: required
services:
    - docker

before_install:
    - docker build -t yasinya/client-test -f ./client/Dockerfile.dev ./client

script:
    - docker run yasinya/client-test npm run test -- --coverage

after_success:
    - docker build -t yasinya/client ./client
    - docker build -t yasinya/api ./server
    - docker build -t yasinya/nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push yasinya/client
    - docker push yasinya/api
    - docker push yasinya/nginx

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: waxqabso
    env: Waxqabso-env
    bucket_name: elasticbeanstalk-us-east-2-100593488730
    bucket_path: waxqabso-path
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: $AWS_SECRET_KEY
