version: "3"
services:
    api:
        image: yasinya/api
        ports:
            - "5000:5000"
        environment:
            - WAXQABSO_DATABASE_URL=${WAXQABSO_DATABASE_URL}
            - SERVICE=${SERVICE}
            - EMAIL=${EMAIL}
            - PASSWORD=${PASSWORD}
            - EMAIL_SECRET=${EMAIL_SECRET}
            - FULL_URL=${FULL_URL}

    client:
        image: yasinya/client
        ports:
            - "3000:3000"

    nginx:
        restart: always
        image: yasinya/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /waxqabso-letsencyrpt/certbot/conf:/etc/letsencrypt
            - /waxqabso-letsencyrpt/certbot/www:/var/www/certbot

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.16.238.0/24
