version: "3"
services:
    postgres:
        image: "postgres:latest"
        restart: always
        volumes:
            - db-data:/var/lib/pg/data
        environment:
            - POSTGRES_DB=${PG_DATABASE}
            - POSTGRES_USER=${PG_USER}
            - POSTGRES_PASSWORD=${PG_PASSWORD}

    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - "5000:5000"
        volumes:
            - /server/node_modules
            - ./server/:/server
        environment:
            - PG_HOST=${PG_HOST}
            - PG_DATABASE=${PG_DATABASE}
            - PG_USER=${PG_USER}
            - PG_PASSWORD=${PG_PASSWORD}
            - PG_PORT=${PG_PORT}
            - SERVICE=${SERVICE}
            - EMAIL=${EMAIL}
            - PASSWORD=${PASSWORD}
            - EMAIL_SECRET=${EMAIL_SECRET}
            - FULL_URL=${FULL_URL}

    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
            - ./client/:/app

    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "8000:80"

volumes:
    db-data:
        driver: local
